import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}
      >
  {/* Navbar Start */}
  <nav className="bg-black p-4">
          
          <ul className="  flex justify-around items-right ">
            <li>
              <a href="/" className="text-white md:text-xl text:[15px] hover:text-red-500">Home</a>
            </li>
            <li>
              <a href="/LiveGames" className="text-white md:text-xl text:[15px] hover:text-red-500">Games</a>
            </li>
            <li>
              <a href="/Contact" className="text-white md:text-xl text:[15px] hover:text-red-500">Contact</a>
            </li>
          </ul>
         
        
      </nav>
      {/* Navbar End */}


        {children}
      </body>
    </html>
  );
}
